import { normalizeDomains } from "@/entities/domain/lib/normalizeDomains"
import type { AppState } from "@/entities/app-state/model/types"
import { STATUS_VALUES } from "@/shared/constants/labels"

const nowIso = () => new Date().toISOString()

export const createSeedData = (): AppState => {
  const createdAt = nowIso()
  const baseDomains = normalizeDomains([])
  return {
    ui: {
      activeWorkspace: "information_request",
      selectedItemId: null,
      /** Task Tree 기본: 도메인은 모두 접힌 상태 */
      expandedDomainIds: [],
      itemsQuery: "",
      treeQuery: "",
      treePreviewItemId: "",
      treeManageDomainId: baseDomains[0]?.id ?? "common",
      typeFilters: [],
      domainFilter: "",
      statusFilter: "",
      priorityFilters: [],
      dueDateFilter: "",
      ownerFilter: "",
      workspaceColumnOrder: [...STATUS_VALUES],
    },
    project: {
      id: "PRJ-001",
      name: "Seolhaewon Project",
      subtitle: "예약엔진 · 웹 · 앱 · 운영정책 협의",
    },
    domains: baseDomains,
    items: [
      {
        id: "IR-001",
        code: "IR-001",
        type: "information_request",
        domain: "reservation",
        title: "객실·골프·식음 상품 마스터 수령",
        description:
          "판매명/운영명, 판매단위/이용단위, 채널, 인원정책, 블랙아웃 캘린더를 수령합니다.",
        priority: "P0",
        status: "논의",
        owner: "고객사 운영팀",
        dueDate: "2026-03-21",
        clientResponse: "",
        finalConfirmedValue: "",
        isLocked: false,
        boardRank: 0,
        createdAt,
        updatedAt: createdAt,
      },
      {
        id: "IR-002",
        code: "IR-002",
        type: "information_request",
        domain: "reservation",
        title: "상품별 재고 차감 단위 확정",
        description: "객실/골프/식음/웰니스/패키지의 inventory grain을 확정합니다.",
        priority: "P0",
        status: "논의",
        owner: "틴토랩 PM",
        dueDate: "2026-03-22",
        clientResponse: "골프와 식음 회차 운영 규칙은 추가 협의 필요",
        finalConfirmedValue: "",
        isLocked: false,
        boardRank: 1,
        createdAt,
        updatedAt: createdAt,
      },
      {
        id: "IR-003",
        code: "IR-003",
        type: "information_request",
        domain: "integration",
        title: "PMS 인터페이스 명세 수령",
        description:
          "예약 생성/변경/취소, 객실상태, 체크인/체크아웃 가능 범위를 확인합니다.",
        priority: "P0",
        status: "논의",
        owner: "고객사 IT팀",
        dueDate: "2026-03-20",
        clientResponse: "조회/생성 API 지원 가능, 변경/취소는 확인 필요",
        finalConfirmedValue: "",
        isLocked: false,
        boardRank: 2,
        createdAt,
        updatedAt: createdAt,
      },
      {
        id: "D-001",
        code: "D-001",
        type: "decision",
        domain: "reservation",
        title: "판매 가능 재고의 authoritative source 확정",
        description:
          "판매 가능 재고와 예약 상태의 기준 시스템을 Reservation Engine으로 둘지 결정합니다.",
        priority: "P0",
        status: "논의",
        owner: "프로젝트 의사결정자",
        dueDate: "2026-03-21",
        clientResponse: "PMS 기준 운영 관성 존재",
        finalConfirmedValue: "",
        isLocked: false,
        boardRank: 3,
        createdAt,
        updatedAt: createdAt,
      },
      {
        id: "D-002",
        code: "D-002",
        type: "decision",
        domain: "reservation",
        title: "패키지 확보 방식을 Group Hold로 확정 후보화",
        description:
          "패키지를 순차예약이 아닌 Group Hold + All-or-Nothing Confirm 구조로 결정합니다.",
        priority: "P0",
        status: "방향합의",
        owner: "틴토랩 CTO",
        dueDate: "2026-03-22",
        clientResponse: "부분 성공은 지양",
        finalConfirmedValue: "Group Hold + All-or-Nothing Confirm 적용",
        isLocked: false,
        boardRank: 0,
        createdAt,
        updatedAt: createdAt,
      },
      {
        id: "D-003",
        code: "D-003",
        type: "decision",
        domain: "web",
        title: "고객 승인 흐름을 화면 상단 고정형으로 노출",
        description:
          "웹/앱/예약 협의 항목 모두 상단에서 상태와 다음 액션이 보이도록 결정합니다.",
        priority: "P1",
        status: "확정",
        owner: "틴토랩 PM",
        dueDate: "2026-03-25",
        clientResponse: "동의",
        finalConfirmedValue: "상단 요약 고정 UI 채택",
        isLocked: true,
        boardRank: 0,
        createdAt,
        updatedAt: createdAt,
      },
      {
        id: "IR-004",
        code: "IR-004",
        type: "information_request",
        domain: "app",
        title: "모바일 앱 로그인 정책 확인",
        description: "회원/비회원, 간편로그인, 본인확인, 예약 조회 정책을 확인합니다.",
        priority: "P1",
        status: "논의",
        owner: "고객사 마케팅팀",
        dueDate: "2026-03-27",
        clientResponse: "",
        finalConfirmedValue: "",
        isLocked: false,
        boardRank: 4,
        createdAt,
        updatedAt: createdAt,
      },
      {
        id: "IR-005",
        code: "IR-005",
        type: "information_request",
        domain: "commerce",
        title: "쇼핑몰 결제·환불 정책 및 영수증 발행 기준 수령",
        description:
          "PG 연동 범위, 부분취소·환불 SLA, 현금영수증/세금계산서 발행 주체를 정리합니다.",
        priority: "P1",
        status: "논의",
        owner: "고객사 재무팀",
        dueDate: "2026-03-28",
        clientResponse: "",
        finalConfirmedValue: "",
        isLocked: false,
        boardRank: 5,
        createdAt,
        updatedAt: createdAt,
      },
      {
        id: "D-004",
        code: "D-004",
        type: "decision",
        domain: "ops",
        title: "야간·피크타임 예약 변경 수수료 정책 초안",
        description:
          "체크인 48시간 이내 변경 시 수수료 부과 여부와 면제 예외를 방향 합의 단계에서 확정합니다.",
        priority: "P1",
        status: "방향합의",
        owner: "고객사 운영팀",
        dueDate: "2026-03-26",
        clientResponse: "성수기 주말은 별도 테이블 필요",
        finalConfirmedValue: "48시간 기준 + 성수기 별표 적용",
        isLocked: false,
        boardRank: 1,
        createdAt,
        updatedAt: createdAt,
      },
      {
        id: "D-005",
        code: "D-005",
        type: "decision",
        domain: "integration",
        title: "외부 채널 예약 동기화 주기 및 충돌 시 우선순위",
        description:
          "OTA·메타검색과의 재고 동기화 주기, 이중예약 방지 시 내부 엔진 우선 규칙을 확정합니다.",
        priority: "P0",
        status: "확정",
        owner: "틴토랩 CTO",
        dueDate: "2026-03-24",
        clientResponse: "동의",
        finalConfirmedValue: "5분 폴링 + 충돌 시 예약엔진 재고 기준",
        isLocked: true,
        boardRank: 1,
        createdAt,
        updatedAt: createdAt,
      },
      {
        id: "RV-001",
        code: "RV-001",
        type: "review",
        domain: "common",
        title: "예약 정책 문구 법무 검토 요청",
        description: "취소·환불·노쇼 관련 고지 문구를 법무 기준에 맞게 검토합니다.",
        priority: "P2",
        status: "논의",
        owner: "틴토랩 PM",
        dueDate: "2026-04-01",
        clientResponse: "",
        finalConfirmedValue: "",
        isLocked: false,
        boardRank: 6,
        createdAt,
        updatedAt: createdAt,
      },
      {
        id: "CR-001",
        code: "CR-001",
        type: "change_request",
        domain: "web",
        title: "예약 완료 화면 CTA 문구 및 트래킹 파라미터 변경",
        description: "전환 캠페인에 맞춰 버튼 문구와 UTM 규칙을 조정합니다.",
        priority: "P3",
        status: "논의",
        owner: "고객사 마케팅팀",
        dueDate: "2026-04-02",
        clientResponse: "",
        finalConfirmedValue: "",
        isLocked: false,
        boardRank: 7,
        createdAt,
        updatedAt: createdAt,
      },
    ],
    comments: [
      {
        id: "C-001",
        itemId: "IR-002",
        author: "틴토랩 PM",
        body: "골프 티타임과 식음 seating shift 기준이 현장 운영 기준표와 일치하는지 확인이 필요합니다.",
        createdAt,
      },
      {
        id: "C-002",
        itemId: "D-001",
        author: "틴토랩 CTO",
        body: "판매 판단 시스템과 현장 운영 시스템을 분리하지 않으면 중복예약과 정합성 복구가 어려워집니다.",
        createdAt,
      },
      {
        id: "C-003",
        itemId: "D-003",
        author: "프로젝트 담당자",
        body: "진행 상태가 한눈에 보여야 이해관계자 간 협의가 쉬워질 것 같습니다.",
        createdAt,
      },
    ],
    history: [
      {
        id: "H-001",
        itemId: "IR-003",
        eventType: "item.updated",
        summary: "고객사 IT팀이 PMS 인터페이스 1차 회신을 등록",
        actor: "고객사 IT팀",
        createdAt,
      },
      {
        id: "H-002",
        itemId: "D-002",
        eventType: "item.agreed",
        summary: "패키지 확보 구조를 Group Hold 방식으로 방향 합의",
        actor: "틴토랩 CTO",
        createdAt,
      },
      {
        id: "H-003",
        itemId: "D-003",
        eventType: "item.locked",
        summary: "상단 고정형 승인 요약 UI를 최종 기준 확정",
        actor: "틴토랩 PM",
        createdAt,
      },
    ],
  }
}
