export {
  FormLabel,
  Heading,
  Overline,
  StatLabel,
  StatSub,
  StatValue,
  Text,
  headingVariants,
  modalCloseIconClassName,
  overlineVariants,
  textVariants,
  type FormLabelProps,
  type HeadingProps,
  type OverlineProps,
  type StatLabelProps,
  type StatSubProps,
  type StatValueProps,
  type TextProps,
} from "@/components/ui/typography"
